(()=>{
'use strict';
const ARGON_ID='a4a2e2fa-0635-46a5-8969-1d0fef40444f';
const ARGON_NAME='SV Argon';
const STORE='basketballApp.selection.v3';
const SUPABASE_URL='https://elpnfmlrkoemjrnzaeok.supabase.co';
const SUPABASE_KEY='sb_publishable_GPzLwaKeevg3e8CNjw9oAQ_50NW2xlg';
const DEFAULT_SELECTION={clubId:ARGON_ID,clubName:ARGON_NAME,clubLogo:'https://images.foys.io/foys/a4a2e2fa-0635-46a5-8969-1d0fef40444f/CC586FA3B4D02C36D9D21FBE50E20E47.gif',teamId:50553,teamGuid:'9b807e1c-8acb-442f-8bb0-35d16bc76e78',teamName:'MSE-2',teamLogo:'https://images.foys.io/foys/a4a2e2fa-0635-46a5-8969-1d0fef40444f/CC586FA3B4D02C36D9D21FBE50E20E47.gif?w=200'};
let sb=null,memberContextCache=null,memberContextAt=0,clubLabelAt=0,clubLabelBusy=false,detailBusy=false,activeMatchId=null,activeMatchTitle='',playerCountsAt=0,playerCountsSig='';
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const isArgon=v=>/^SV Argon(?:\s|$)/i.test(String(v||'').trim());
function esc(value){return String(value??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function injectStyle(){
 if(document.getElementById('argonUiStyle'))return;
 const style=document.createElement('style');style.id='argonUiStyle';style.textContent='.maps-link{font-weight:850;color:#245d9c;text-decoration:none}.drivers-list{margin-top:10px;border:1px solid var(--line);border-radius:10px;padding:10px}.drivers-list strong{display:block;font-size:10px;margin-bottom:5px}.drivers-names{display:flex;gap:5px;flex-wrap:wrap}.driver-name{display:inline-flex;border-radius:999px;padding:5px 8px;background:#eef0f5;color:var(--navy);font-size:8px;font-weight:850}.club-tab-label{display:block}.player-count{display:block;margin-top:4px;font-size:11px;font-weight:800;color:var(--navy)}.final-start{display:block;margin-bottom:3px;font-size:11px;font-weight:800;color:var(--muted)}.attendees-list{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.attendee-name{display:inline-flex;border-radius:999px;padding:6px 9px;background:#eef0f5;color:var(--navy);font-size:11px;font-weight:850}';document.head.appendChild(style);
}
async function getClient(){
 if(sb)return sb;
 const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');
 sb=mod.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});
 sb.auth.onAuthStateChange(()=>{memberContextCache=null;memberContextAt=0;clubLabelAt=0;playerCountsAt=0;schedule()});
 return sb;
}
function lockSelection(){try{const raw=localStorage.getItem(STORE);if(!raw)return false;const value=JSON.parse(raw);if(value?.clubId===ARGON_ID)return false;localStorage.setItem(STORE,JSON.stringify(DEFAULT_SELECTION));location.reload();return true}catch{return false}}
if(lockSelection())return;
function fixTeamUi(){const select=document.getElementById('teamSelect');if(select)[...select.options].filter(o=>o.value==='__change_club__').forEach(o=>o.remove());const button=document.getElementById('changeTeamBtn');if(button)button.textContent='Team wijzigen';const settingsClub=document.getElementById('settingsClub');if(settingsClub)settingsClub.textContent=ARGON_NAME;const title=document.getElementById('teamModalTitle');if(title)title.textContent='Team kiezen';const sheet=document.querySelector('#teamModal .team-sheet');if(sheet){const intro=sheet.querySelector('.sheet-title-row p');if(intro)intro.textContent='Kies een team van SV Argon of Alle teams.';sheet.querySelectorAll('.search-label,.search-row,.search-status,.club-results,.chosen-club-head').forEach(el=>el.style.display='none');const chosen=document.getElementById('chosenClub');if(chosen)chosen.hidden=false;const name=document.getElementById('chosenClubName');if(name)name.textContent=ARGON_NAME}}
function addressAfterBreak(meta){let after=false,text='';for(const node of meta.childNodes){if(node.nodeName==='BR'){after=true;continue}if(after&&node.nodeType===Node.TEXT_NODE)text+=node.textContent||''}return text.trim()}
function addMapsLinks(){document.querySelectorAll('article.event[data-match-id] .meta').forEach(meta=>{if(meta.querySelector('.maps-link'))return;const address=addressAfterBreak(meta);if(!address)return;const link=document.createElement('a');link.className='maps-link';link.href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Maps';link.setAttribute('aria-label',`Open ${address} in Google Maps`);meta.append(document.createTextNode(' · '),link)})}
function setClubLabel(label){const tab=document.querySelector('.tab[data-view="club"]');if(!tab)return;const current=tab.querySelector('.club-tab-label')?.textContent||'';if(current===label)return;tab.innerHTML=`<span class="tab-icon">●</span><span class="club-tab-label">${label}</span>`}
async function updateClubTab(force=false){if(clubLabelBusy||(!force&&Date.now()-clubLabelAt<900))return;const tab=document.querySelector('.tab[data-view="club"]');if(!tab)return;clubLabelBusy=true;try{const s=await getClient(),{data:{session}}=await s.auth.getSession();if(!session){setClubLabel('Club/inloggen');return}const {data:m,error}=await s.rpc('sync_current_member');if(error){setClubLabel('Club');return}if(m?.active&&m?.role==='admin'&&m?.is_trainer)setClubLabel('Club/admin/trainer');else if(m?.active&&m?.role==='admin')setClubLabel('Club/admin');else if(m?.active&&m?.is_trainer)setClubLabel('Club/trainer');else setClubLabel('Club')}catch{const root=document.getElementById('clubRoot');setClubLabel(root?.querySelector('[data-clubview="admin"]')?'Club/admin':root?.querySelector('.auth-box h2')?'Club/inloggen':'Club')}finally{clubLabelAt=Date.now();clubLabelBusy=false}}
async function memberContext(force=false){if(!force&&memberContextCache&&Date.now()-memberContextAt<15000)return memberContextCache;const s=await getClient(),{data:{session}}=await s.auth.getSession();if(!session)return null;const {data:m,error}=await s.rpc('sync_current_member');if(error||!m?.active)return null;const {data:rows}=await s.from('member_teams').select('team_id,teams(id,team_name,foy_team_guid)').eq('member_id',m.id);memberContextCache={member:m,teams:(rows||[]).map(x=>x.teams?{...x.teams,id:x.team_id}:null).filter(Boolean)};memberContextAt=Date.now();return memberContextCache}
function detailTeams(){const title=document.getElementById('matchDetailTitle')?.textContent?.trim()||'';const parts=title.split(/\s+[—–-]\s+/).map(x=>x.trim()).filter(Boolean);return{title,home:parts[0]||'',away:parts[1]||''}}
function detailLocation(){const spans=[...document.querySelectorAll('#matchDetailBody .match-summary span')];return spans.at(-1)?.textContent?.trim()||''}
function isAwayDetail(home,away,location){return !isArgon(home)&&isArgon(away)&&!/eendracht|phoenix/i.test(location)}
function argonTeamName(home,away){const side=isArgon(home)?home:isArgon(away)?away:'';return side.replace(/^SV Argon\s*/i,'').trim()}
function resolveMatchId(title){if(activeMatchId&&(!activeMatchTitle||norm(activeMatchTitle)===norm(title)))return Number(activeMatchId);const card=[...document.querySelectorAll('article.event[data-match-id]')].find(c=>norm(c.querySelector('.match-title')?.textContent)===norm(title));return card?Number(card.dataset.matchId):null}
function cachedMatches(){try{const s=JSON.parse(localStorage.getItem(STORE)||'{}'),raw=localStorage.getItem(`basketballApp.matches.v3.${s.teamGuid||''}`);return raw?(JSON.parse(raw)?.matches||[]):[]}catch{return[]}}
function cachedMatch(id){return cachedMatches().find(m=>String(m.id)===String(id))||null}
function addFinalStartTimes(){for(const card of document.querySelectorAll('#agendaList article.event[data-match-id],#gamesList article.event[data-match-id]')){if(card.querySelector('.final-start'))continue;const m=cachedMatch(card.dataset.matchId);if(!m||m.homeScore===null||m.homeScore===undefined||m.awayScore===null||m.awayScore===undefined)continue;const meta=card.querySelector('.meta');if(!meta)continue;const start=String(m.startTime||'').slice(0,5);if(!start)continue;const el=document.createElement('span');el.className='final-start';el.textContent=`Start ${start}`;meta.prepend(el)}}
async function addPlayerCounts(){const cards=[...document.querySelectorAll('#agendaList article.event[data-match-id],#gamesList article.event[data-match-id]')],ids=[...new Set(cards.map(c=>Number(c.dataset.matchId)).filter(Number.isFinite))],sig=ids.sort((a,b)=>a-b).join(',');if(!ids.length)return;if(sig===playerCountsSig&&Date.now()-playerCountsAt<5000)return;const s=await getClient(),{data,error}=await s.rpc('get_match_player_counts',{p_match_ids:ids});if(error)return;const map=new Map((data||[]).map(x=>[String(x.foy_match_id),Number(x.player_count)||0]));for(const card of cards){let el=card.querySelector('.player-count');if(!el){el=document.createElement('span');el.className='player-count';(card.querySelector('.meta')||card).appendChild(el)}el.textContent=`Spelers: ${map.get(String(card.dataset.matchId))||0}`}playerCountsSig=sig;playerCountsAt=Date.now()}
async function ownAttendance(matchId,memberId){const s=await getClient(),{data}=await s.from('attendance').select('attending,driving').eq('foy_match_id',Number(matchId)).eq('member_id',memberId).maybeSingle();return data||null}
async function drivers(matchId){const s=await getClient(),{data,error}=await s.rpc('get_match_drivers',{p_match_id:Number(matchId)});if(error)return[];return data||[]}
async function attendees(matchId){const s=await getClient(),{data,error}=await s.rpc('get_match_attendees',{p_match_id:Number(matchId)});if(error)return[];return data||[]}
function applyAttendanceVisual(state,away){const yes=document.querySelector('#matchDetailBody [data-pres="yes"]'),no=document.querySelector('#matchDetailBody [data-pres="no"]'),input=document.getElementById('drive');if(yes){yes.classList.toggle('selected',state?.attending===true);yes.classList.toggle('yes',state?.attending===true)}if(no){no.classList.toggle('selected',state?.attending===false);no.classList.toggle('no',state?.attending===false)}if(input){input.checked=away&&state?.driving===true;input.disabled=!away}}
async function renderDrivers(matchId){let box=document.querySelector('#matchDetailBody .drivers-list');if(!box){const toggle=document.querySelector('#matchDetailBody .drive-toggle');if(!toggle)return;box=document.createElement('div');box.className='drivers-list';toggle.insertAdjacentElement('afterend',box)}const rows=await drivers(matchId);box.innerHTML=`<strong>Rijders</strong><div class="drivers-names">${rows.length?rows.map(r=>`<span class="driver-name">${esc(r.full_name||'Lid')}</span>`).join(''):'<span class="match-muted">Nog niemand heeft aangegeven te rijden.</span>'}</div>`}
async function renderAttendees(matchId,showEmpty=true){const body=document.getElementById('matchDetailBody');if(!body)return;const rows=await attendees(matchId);let section=body.querySelector('.attendees-section');if(!rows.length&&!showEmpty){section?.remove();return}if(!section){section=document.createElement('div');section.className='match-detail-section attendees-section';const taskSection=[...body.querySelectorAll('.match-detail-section')].find(x=>x.querySelector('h3')?.textContent?.trim()==='Taken');if(taskSection)taskSection.insertAdjacentElement('beforebegin',section);else body.appendChild(section)}section.innerHTML=`<h3>Aanwezige spelers</h3>${rows.length?`<div class="attendees-list">${rows.map(r=>`<span class="attendee-name">${esc(r.full_name||'Lid')}</span>`).join('')}</div>`:'<p class="match-muted">Nog niemand heeft zich aanwezig gemeld.</p>'}`}
async function saveAttendance(ctx,attending){const input=document.getElementById('drive'),driving=!!(attending&&ctx.away&&input?.checked),s=await getClient();const {data,error}=await s.rpc('set_match_attendance',{p_match_id:ctx.matchId,p_team_id:ctx.team.id,p_attending:attending,p_driving:driving});if(error){window.alert(error.message);return}applyAttendanceVisual(data,ctx.away);if(ctx.away)await renderDrivers(ctx.matchId);await renderAttendees(ctx.matchId,true);playerCountsAt=0;schedule()}
async function saveDriving(ctx,checked){const s=await getClient(),{data,error}=await s.rpc('set_match_attendance',{p_match_id:ctx.matchId,p_team_id:ctx.team.id,p_attending:true,p_driving:!!checked});if(error){window.alert(error.message);return}applyAttendanceVisual(data,true);await renderDrivers(ctx.matchId);await renderAttendees(ctx.matchId,true);playerCountsAt=0;schedule()}
async function configureDetail(){if(detailBusy)return;const overlay=document.getElementById('matchDetailOverlay');if(!overlay||overlay.hidden)return;detailBusy=true;try{const dt=detailTeams(),matchId=resolveMatchId(dt.title);if(!matchId)return;const context=await memberContext();if(!context)return;const teamName=argonTeamName(dt.home,dt.away),team=context.teams.find(x=>norm(x.team_name)===norm(teamName));await renderAttendees(matchId,!!team);if(!team)return;const yes=document.querySelector('#matchDetailBody [data-pres="yes"]'),no=document.querySelector('#matchDetailBody [data-pres="no"]'),toggle=document.querySelector('#matchDetailBody .drive-toggle');if(!yes&&!no&&!toggle)return;const away=isAwayDetail(dt.home,dt.away,detailLocation()),ctx={matchId,team,away},input=document.getElementById('drive');const signature=`${matchId}:${team.id}:${away?'away':'home'}`;const alreadyBound=overlay.dataset.argonDetailSignature===signature&&(!yes||yes.dataset.argonBound==='1')&&(!no||no.dataset.argonBound==='1')&&(!input||input.dataset.argonBound==='1')&&(!away||!!document.querySelector('#matchDetailBody .drivers-list'));if(alreadyBound)return;overlay.dataset.argonDetailSignature=signature;if(toggle){toggle.style.display=away?'flex':'none';toggle.classList.remove('disabled')}if(input){input.disabled=!away;input.onchange=null;if(!input.dataset.argonBound){input.dataset.argonBound='1';input.addEventListener('change',()=>saveDriving(ctx,input.checked))}}for(const [button,value] of [[yes,true],[no,false]])if(button){button.onclick=null;if(!button.dataset.argonBound){button.dataset.argonBound='1';button.addEventListener('click',()=>saveAttendance(ctx,value))}}let state=await ownAttendance(matchId,context.member.id);if(!away&&state?.driving){const s=await getClient(),{data}=await s.rpc('set_match_attendance',{p_match_id:matchId,p_team_id:team.id,p_attending:state.attending===true,p_driving:false});state=data||state}applyAttendanceVisual(state,away);const old=document.querySelector('#matchDetailBody .drivers-list');if(!away)old?.remove();else await renderDrivers(matchId)}finally{detailBusy=false}}
let queued=false;
async function apply(){queued=false;injectStyle();fixTeamUi();addMapsLinks();addFinalStartTimes();await addPlayerCounts();await updateClubTab();await configureDetail()}
function schedule(){if(queued)return;queued=true;setTimeout(apply,0)}
document.addEventListener('click',e=>{const card=e.target.closest('article.event[data-match-id],article.event[data-task-id]');if(card){if(card.dataset.matchId){activeMatchId=Number(card.dataset.matchId);activeMatchTitle=card.querySelector('.match-title')?.textContent||''}else{activeMatchId=null;activeMatchTitle=''}}schedule()},true);
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class']});
document.addEventListener('DOMContentLoaded',()=>{schedule();setTimeout(()=>updateClubTab(true),500)});
})();