(()=>{
'use strict';
const SUPABASE_URL='https://elpnfmlrkoemjrnzaeok.supabase.co';
const SUPABASE_KEY='sb_publishable_GPzLwaKeevg3e8CNjw9oAQ_50NW2xlg';
const FEDERATION_ID='52cfa65e-9782-4a81-ab35-e2f981fcb7a9';
const ARGON_CLUB_ID='a4a2e2fa-0635-46a5-8969-1d0fef40444f';
const ARGON_CLUB_NAME='SV Argon';
let supabase=null,session=null,member=null,teams=[],memberTeams=[],members=[],memberTeamRows=[];
let taskEvents=[],trainings=[],attendanceRows=[],notifications=[],swaps=[],matchRows=[];
let realtimeChannels=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const dateOnly=v=>String(v||'').slice(0,10);
const timeOnly=v=>String(v||'').slice(0,5);
const fmtDate=v=>{try{return new Intl.DateTimeFormat('nl-NL',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${dateOnly(v)}T12:00:00`))}catch{return v}};
const seasonRange=()=>{const n=new Date(),y=n.getMonth()>=6?n.getFullYear():n.getFullYear()-1;return {start:`${y}-07-01`,end:`${y+1}-06-30`}};
const roleLabel=r=>r==='referee'?'Scheidsrechter':r==='table'?'Tafel':'Taak';
function toast(m){const e=$('toast');if(!e)return alert(m);e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function inject(){
 if($('view-club'))return;
 const link=document.createElement('link');link.rel='stylesheet';link.href='./club.css?v=1';document.head.appendChild(link);
 const main=document.querySelector('main');
 const section=document.createElement('section');section.id='view-club';section.className='view';section.innerHTML=`<div class="section-head"><div><h1>Club</h1><p>Leden, aanwezigheid, trainingen, taken en beheer.</p></div></div><div id="clubRoot"><div class="empty">Ledenomgeving laden…</div></div>`;main.appendChild(section);
 const nav=document.querySelector('.tabs');const b=document.createElement('button');b.className='tab';b.dataset.view='club';b.type='button';b.innerHTML='<span class="tab-icon">●</span>Club';b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-club'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===b));});nav.appendChild(b);
}
async function init(){
 inject();
 try{
  const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');
  supabase=mod.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});
  const {data}=await supabase.auth.getSession();session=data.session;
  supabase.auth.onAuthStateChange(async(_e,s)=>{session=s;await refreshMember();});
  await refreshMember();
 }catch(e){console.error(e);$('clubRoot').innerHTML='<div class="empty error-box">De ledenomgeving kon niet worden geladen.</div>'}
}
async function refreshMember(){
 clearRealtime();
 if(!session){member=null;renderLoggedOut();return}
 try{
  const {data,error}=await supabase.rpc('sync_current_member');if(error)throw error;member=data;
  if(member?.active){await loadBaseData();try{setupRealtime();}catch(realtimeError){console.warn('Realtime kon niet starten; Club blijft bruikbaar.',realtimeError);}}
  renderClub();
 }catch(e){console.error(e);$('clubRoot').innerHTML=`<div class="empty error-box">${esc(e.message||'Account kon niet worden geladen.')}</div>`}
}
function renderLoggedOut(){
 $('clubRoot').innerHTML=`<div class="club-card-panel auth-box"><h2>Ledenlogin</h2><p>Alleen geregistreerde clubleden krijgen toegang tot aanwezigheid, taakwissels en de beheerfuncties.</p><form id="loginForm" class="club-form"><label>E-mailadres<input id="loginEmail" type="email" required autocomplete="email" placeholder="jij@voorbeeld.nl"></label><button class="primary-button" type="submit">Stuur inloglink</button></form><div class="auth-message">Je ontvangt een beveiligde eenmalige inloglink per e-mail. Een account dat nog niet door een admin aan de ledenadministratie is gekoppeld blijft geblokkeerd.</div></div>`;
 $('loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('loginEmail').value.trim();if(!email)return;const {error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:true,emailRedirectTo:location.origin+location.pathname}});if(error)toast(error.message);else toast('Inloglink verstuurd. Controleer je e-mail.');});
}
async function signOut(){await supabase.auth.signOut();}
async function loadBaseData(){
 const [t,mt,te,tr,at,no,sw]=await Promise.all([
  supabase.from('teams').select('*').eq('active',true).order('team_name'),
  supabase.from('member_teams').select('team_id,teams(*)').eq('member_id',member.id),
  supabase.from('task_events').select('*,task_assignments(*)').eq('active',true).order('event_date').order('start_time'),
  supabase.from('training_sessions').select('*,teams(team_name)').order('training_date').order('start_time'),
  supabase.from('attendance').select('*').eq('member_id',member.id),
  supabase.from('notifications').select('*').eq('recipient_member_id',member.id).order('created_at',{ascending:false}).limit(100),
  supabase.from('task_swap_requests').select('*,task_assignments(*,task_events(*))').eq('status','open').order('created_at',{ascending:false})
 ]);
 [t,mt,te,tr,at,no,sw].forEach(r=>{if(r.error)console.warn(r.error)});
 teams=t.data||[];memberTeams=(mt.data||[]).map(x=>x.teams).filter(Boolean);taskEvents=te.data||[];trainings=tr.data||[];attendanceRows=at.data||[];notifications=no.data||[];swaps=sw.data||[];
 if(member.role==='admin')await loadAdminData();
 await loadMemberMatches();
}
async function loadAdminData(){
 const [m,mt]=await Promise.all([supabase.from('members').select('*').order('full_name'),supabase.from('member_teams').select('*')]);
 members=m.data||[];memberTeamRows=mt.data||[];
}
async function ensureAdminBootstrapData(){
 if(member?.role!=='admin')return;
 await syncArgonTeams();
 const {count}=await supabase.from('task_events').select('id',{count:'exact',head:true});
 if(!count)await importLegacyTasks();
 await loadBaseData();
}
async function syncArgonTeams(){
 try{
  const r=await fetch(`https://api.foys.io/competition/public-api/v1/organisations/${ARGON_CLUB_ID}/teams`,{headers:{Accept:'application/json','X-FederationID':FEDERATION_ID},cache:'no-store'});if(!r.ok)throw new Error('FOYS teams niet bereikbaar');const rows=await r.json();
  const payload=(Array.isArray(rows)?rows:[]).filter(x=>x.guid).map(x=>({club_id:ARGON_CLUB_ID,club_name:ARGON_CLUB_NAME,foy_team_guid:x.guid,foy_team_id:x.id,team_name:x.name,active:true}));
  if(payload.length){const {error}=await supabase.from('teams').upsert(payload,{onConflict:'foy_team_guid'});if(error)throw error;}
 }catch(e){console.warn(e);}
}
function findTeamForHome(home,teamList){const name=String(home||'').replace(/^SV Argon\s+/i,'').trim();return teamList.find(t=>t.team_name===name)?.id||null}
async function importLegacyTasks(){
 try{
  const r=await fetch('./data/tasks.json',{cache:'no-store'}),j=await r.json();
  const {data:dbTeams}=await supabase.from('teams').select('*');
  for(const row of j.tasks||[]){
   const {data:event,error}=await supabase.from('task_events').insert({legacy_id:row.id,team_id:findTeamForHome(row.home,dbTeams||[]),event_date:row.date,arrival_time:row.arrivalTime,start_time:row.startTime,home:row.home,away:row.away,location:row.location,field:row.field,active:true,created_by:member.id}).select().single();
   if(error){if(error.code==='23505')continue;throw error}
   const assignments=[];(row.referees||[]).forEach((name,i)=>assignments.push({task_event_id:event.id,assigned_name:name,role:'referee',slot:i+1}));(row.table||[]).forEach((name,i)=>assignments.push({task_event_id:event.id,assigned_name:name,role:'table',slot:i+1}));
   if(assignments.length){const {error:aerr}=await supabase.from('task_assignments').insert(assignments);if(aerr)throw aerr;}
  }
 }catch(e){console.error('Import taken',e);toast('Bestaand takenschema kon niet volledig worden geïmporteerd.');}
}
async function loadMemberMatches(){
 const source=memberTeams;const guids=[...new Set(source.map(t=>t.foy_team_guid).filter(Boolean))];if(!guids.length){matchRows=[];return}
 const range=seasonRange(),byId=new Map();let cursor=0;
 const workers=Array.from({length:Math.min(4,guids.length)},async()=>{while(cursor<guids.length){const guid=guids[cursor++];let skip=0,total=Infinity;while(skip<total){const p=new URLSearchParams({startDate:range.start,endDate:range.end,teamGuid:guid,skipCount:String(skip),maxResultCount:'100',sorting:'date asc, startTime asc'});const r=await fetch(`https://api.foys.io/competition/public-api/v1/matches?${p}`,{headers:{Accept:'application/json','X-FederationID':FEDERATION_ID},cache:'no-store'});if(!r.ok)break;const j=await r.json(),rows=j.items||[];rows.forEach(x=>byId.set(String(x.id),x));total=Number(j.totalCount)||rows.length;skip+=rows.length;if(!rows.length||rows.length<100)break;}}});
 await Promise.all(workers);matchRows=[...byId.values()].sort((a,b)=>`${a.date}T${a.startTime}`.localeCompare(`${b.date}T${b.startTime}`));
}
function renderClub(){
 if(!session){renderLoggedOut();return}
 if(!member?.active){renderPending();return}
 const unread=notifications.filter(n=>!n.read_at).length;
 $('clubRoot').innerHTML=`<div class="club-card-panel"><div class="club-row-head"><div><h2>${esc(member.full_name||member.email||'Lid')}</h2><p>${member.role==='admin'?'Administrator':'Lid'} · ${esc(member.email||member.phone||'')}</p></div><button class="mini-button" id="logoutBtn">Uitloggen</button></div>${memberTeams.length?`<div>${memberTeams.map(t=>`<span class="club-pill">${esc(t.team_name)}</span>`).join('')}</div>`:'<p>Nog geen teams gekoppeld.</p>'}</div><div class="club-section-tabs" id="clubTabs"><button data-clubview="clubagenda" class="active">Agenda</button><button data-clubview="presence">Aanwezigheid</button><button data-clubview="mytasks">Mijn taken</button><button data-clubview="swaps">Wisselen</button><button data-clubview="notices">Meldingen${unread?'<span class="notification-dot"></span>':''}</button>${member.role==='admin'?'<button data-clubview="admin">Admin</button>':''}</div><div id="club-sub-clubagenda" class="club-subview active"></div><div id="club-sub-presence" class="club-subview"></div><div id="club-sub-mytasks" class="club-subview"></div><div id="club-sub-swaps" class="club-subview"></div><div id="club-sub-notices" class="club-subview"></div>${member.role==='admin'?'<div id="club-sub-admin" class="club-subview"></div>':''}`;
 $('logoutBtn').onclick=signOut;document.querySelectorAll('#clubTabs button').forEach(b=>b.onclick=()=>switchClubView(b.dataset.clubview));
 renderClubAgenda();renderAttendance();renderMyTasks();renderSwaps();renderNotifications();if(member.role==='admin')renderAdmin();
}
function renderPending(){
 $('clubRoot').innerHTML=`<div class="club-card-panel auth-box"><h2>Account nog niet actief</h2><p>Je bent veilig ingelogd, maar dit account is nog niet gekoppeld aan een actief lid.</p><div class="auth-message">Een admin kan jouw e-mailadres toevoegen aan de ledenadministratie en één of meerdere teams koppelen. Daarna krijg je automatisch toegang.</div><div id="firstAdminBox" class="club-card-panel"><h3>Eerste administrator instellen</h3><p>Alleen voor de eerste beheerder van deze nieuwe installatie.</p><form id="claimAdminForm" class="club-form"><label>Eenmalige setupcode<input id="adminSetupCode" class="bootstrap-code" required></label><button class="primary-button" type="submit">Maak mij eerste admin</button></form></div><div class="club-actions"><button class="mini-button" id="pendingRefresh">Opnieuw controleren</button><button class="mini-button" id="pendingLogout">Uitloggen</button></div></div>`;
 $('pendingRefresh').onclick=refreshMember;$('pendingLogout').onclick=signOut;$('claimAdminForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await supabase.rpc('claim_first_admin',{p_code:$('adminSetupCode').value.trim()});if(error){toast(error.message);return}member=data;toast('Eerste admin geactiveerd.');await ensureAdminBootstrapData();renderClub();};
}
function switchClubView(name){document.querySelectorAll('#clubTabs button').forEach(b=>b.classList.toggle('active',b.dataset.clubview===name));document.querySelectorAll('.club-subview').forEach(v=>v.classList.toggle('active',v.id===`club-sub-${name}`));if(name==='notices')markNotificationsRead();}
function renderClubAgenda(){
 const target=$('club-sub-clubagenda');if(!target)return;const rows=[];
 trainings.forEach(t=>rows.push({kind:'training',date:t.training_date,time:t.start_time,data:t}));
 taskEvents.forEach(t=>rows.push({kind:'task',date:t.event_date,time:t.arrival_time||t.start_time,data:t}));
 rows.sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`));
 target.innerHTML=`<div class="club-card-panel"><h2>${member.role==='admin'?'Beheeragenda':'Clubagenda'}</h2><p>Trainingen en beheerde taken uit de clubadministratie.</p><div class="club-list">${rows.length?rows.map(x=>x.kind==='training'?trainingCard(x.data):taskEventCard(x.data)).join(''):'<div class="club-empty">Nog geen trainingen of taken.</div>'}</div></div>`;
}
function trainingCard(t){return `<div class="club-row"><div class="club-row-head"><div><span class="club-pill">Training</span><strong>${esc(t.title)}</strong><small>${esc(fmtDate(t.training_date))} · ${esc(timeOnly(t.start_time))}${t.end_time?' - '+esc(timeOnly(t.end_time)):''}<br>${esc(t.teams?.team_name||'Hele vereniging')} · ${esc(t.location||'Locatie niet ingevuld')}</small></div></div>${t.notes?`<small>${esc(t.notes)}</small>`:''}</div>`}
function taskEventCard(t){const a=t.task_assignments||[];return `<div class="club-row"><div><span class="club-pill">Taak</span><strong>${esc(t.home)} — ${esc(t.away)}</strong><small>${esc(fmtDate(t.event_date))} · aanwezig ${esc(timeOnly(t.arrival_time||t.start_time))} · wedstrijd ${esc(timeOnly(t.start_time))}<br>${esc(t.location||'')} ${esc(t.field||'')}</small></div>${a.length?`<small>${a.map(x=>`${roleLabel(x.role)}: ${esc(x.assigned_name||'Niet toegewezen')}`).join('<br>')}</small>`:''}</div>`}
function teamLabel(m,side){const sponsor=m[`${side}TeamSponsorClubName`],org=m[`${side}Organisation`]?.name,tn=m[`${side}TeamName`]||'';return [sponsor||org,tn].filter(Boolean).join(' ').trim()}
function renderAttendance(){
 const target=$('club-sub-presence');if(!target)return;const today=new Date().toISOString().slice(0,10),rows=matchRows.filter(m=>dateOnly(m.date)>=today);const byMatch=new Map(attendanceRows.map(a=>[String(a.foy_match_id),a.attending]));
 target.innerHTML=`<div class="club-card-panel"><h2>Aanwezigheid</h2><p>Kies per wedstrijd uitsluitend Ja of Nee. Geen reactie blijft administratief ‘nog niet gereageerd’.</p><div class="club-list">${rows.length?rows.map(m=>{const s=byMatch.get(String(m.id));return `<div class="club-row"><strong>${esc(teamLabel(m,'home'))} — ${esc(teamLabel(m,'away'))}</strong><small>${esc(fmtDate(m.date))} · ${esc(timeOnly(m.startTime))} · ${esc(m.accommodationName||'')}</small><div class="attendance-choice"><button class="mini-button yes ${s===true?'selected':''}" data-attend="yes" data-match="${esc(m.id)}">Ja</button><button class="mini-button no ${s===false?'selected':''}" data-attend="no" data-match="${esc(m.id)}">Nee</button></div></div>`}).join(''):'<div class="club-empty">Geen komende wedstrijden voor jouw teams.</div>'}</div></div>`;
 target.querySelectorAll('[data-attend]').forEach(b=>b.onclick=()=>saveAttendance(b.dataset.match,b.dataset.attend==='yes'));
}
async function saveAttendance(matchId,value){const {error}=await supabase.from('attendance').upsert({foy_match_id:Number(matchId),member_id:member.id,attending:value,updated_at:new Date().toISOString()},{onConflict:'foy_match_id,member_id'});if(error)return toast(error.message);const i=attendanceRows.findIndex(a=>String(a.foy_match_id)===String(matchId));const row={foy_match_id:Number(matchId),member_id:member.id,attending:value};if(i>=0)attendanceRows[i]=row;else attendanceRows.push(row);renderAttendance();toast(value?'Aanwezig: Ja':'Aanwezig: Nee')}
function myAssignments(){return taskEvents.flatMap(e=>(e.task_assignments||[]).filter(a=>a.assigned_member_id===member.id||(!a.assigned_member_id&&String(a.assigned_name).trim().toLowerCase()===String(member.full_name).trim().toLowerCase())).map(a=>({event:e,assignment:a}))).sort((a,b)=>`${a.event.event_date}T${a.event.start_time}`.localeCompare(`${b.event.event_date}T${b.event.start_time}`))}
function renderMyTasks(){const target=$('club-sub-mytasks');if(!target)return;const mine=myAssignments();target.innerHTML=`<div class="club-card-panel"><h2>Mijn taken</h2><p>Vraag hier een wissel aan voor een taak die aan jou is toegewezen.</p><div class="club-list">${mine.length?mine.map(x=>{const open=swaps.some(s=>s.assignment_id===x.assignment.id);return `<div class="club-row"><strong>${esc(roleLabel(x.assignment.role))} · ${esc(x.event.home)} — ${esc(x.event.away)}</strong><small>${esc(fmtDate(x.event.event_date))} · aanwezig ${esc(timeOnly(x.event.arrival_time||x.event.start_time))}</small><div class="mini-actions"><button class="mini-button ${open?'':'primary'}" data-swap-request="${x.assignment.id}" ${open?'disabled':''}>${open?'Wissel staat open':'Taak wisselen'}</button></div></div>`}).join(''):'<div class="club-empty">Geen taken aan jou gekoppeld.</div>'}</div></div>`;target.querySelectorAll('[data-swap-request]').forEach(b=>b.onclick=()=>requestSwap(b.dataset.swapRequest));}
async function requestSwap(id){const {error}=await supabase.rpc('request_task_swap',{p_assignment_id:id});if(error)return toast(error.message);toast('Taakwissel staat open voor andere leden.');await reloadDynamic();}
function renderSwaps(){const target=$('club-sub-swaps');if(!target)return;target.innerHTML=`<div class="club-card-panel"><h2>Open taakwissels</h2><p>Een taak kan maar één keer worden overgenomen. De eerste geldige overname wordt direct vastgelegd.</p><div class="club-list">${swaps.length?swaps.map(s=>{const a=s.task_assignments||{},e=a.task_events||{};const own=s.requested_by===member.id;return `<div class="club-row"><strong>${esc(roleLabel(a.role))} · ${esc(e.home||'Taak')} — ${esc(e.away||'')}</strong><small>${esc(fmtDate(e.event_date||s.created_at))} · ${esc(a.assigned_name||'')}</small><div class="mini-actions">${own?`<button class="mini-button danger" data-cancel-swap="${s.id}">Annuleren</button>`:`<button class="mini-button primary" data-accept-swap="${s.id}">Taak overnemen</button>`}</div></div>`}).join(''):'<div class="club-empty">Geen open wisselverzoeken.</div>'}</div></div>`;target.querySelectorAll('[data-accept-swap]').forEach(b=>b.onclick=()=>acceptSwap(b.dataset.acceptSwap));target.querySelectorAll('[data-cancel-swap]').forEach(b=>b.onclick=()=>cancelSwap(b.dataset.cancelSwap));}
async function acceptSwap(id){const {error}=await supabase.rpc('accept_task_swap',{p_request_id:id});if(error)return toast(error.message);toast('Taak is aan jou toegewezen.');await reloadDynamic()}
async function cancelSwap(id){const {error}=await supabase.rpc('cancel_task_swap',{p_request_id:id});if(error)return toast(error.message);toast('Wissel geannuleerd.');await reloadDynamic()}
function renderNotifications(){const target=$('club-sub-notices');if(!target)return;target.innerHTML=`<div class="club-card-panel"><h2>Meldingen</h2><div class="club-list">${notifications.length?notifications.map(n=>`<div class="club-row ${n.read_at?'':'notice-unread'}"><strong>${esc(n.title)}</strong><small>${esc(n.message)}<br>${esc(new Intl.DateTimeFormat('nl-NL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(n.created_at)))}</small></div>`).join(''):'<div class="club-empty">Geen meldingen.</div>'}</div></div>`}
async function markNotificationsRead(){const unread=notifications.filter(n=>!n.read_at).map(n=>n.id);if(!unread.length)return;await supabase.from('notifications').update({read_at:new Date().toISOString()}).in('id',unread);notifications.forEach(n=>{if(unread.includes(n.id))n.read_at=new Date().toISOString()});renderNotifications();}
async function reloadDynamic(){await loadBaseData();renderClub();}
function teamOptions(selected=''){return `<option value="">Hele vereniging / geen team</option>`+teams.map(t=>`<option value="${t.id}" ${selected===t.id?'selected':''}>${esc(t.team_name)}</option>`).join('')}
function memberOptions(selected=''){return `<option value="">Niet gekoppeld / naam handmatig</option>`+members.filter(m=>m.active).map(m=>`<option value="${m.id}" ${selected===m.id?'selected':''}>${esc(m.full_name||m.email)}</option>`).join('')}
function renderAdmin(){
 const target=$('club-sub-admin');if(!target)return;target.innerHTML=`<div class="club-card-panel"><h2>Adminbeheer</h2><p>Beheer leden, meerdere teams per lid, trainingen en taken. Wijzigingen staan centraal in Supabase en zijn direct voor leden beschikbaar.</p><div class="club-section-tabs" id="adminTabs"><button data-adminview="members" class="active">Leden</button><button data-adminview="agenda">Agenda beheren</button></div><div id="admin-members"></div><div id="admin-agenda" hidden></div></div>`;document.querySelectorAll('#adminTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#adminTabs button').forEach(x=>x.classList.toggle('active',x===b));$('admin-members').hidden=b.dataset.adminview!=='members';$('admin-agenda').hidden=b.dataset.adminview!=='agenda';});renderAdminMembers();renderAdminAgenda();}
function renderAdminMembers(editId=''){const target=$('admin-members');const edit=members.find(m=>m.id===editId);const selectedTeams=new Set(memberTeamRows.filter(x=>x.member_id===editId).map(x=>x.team_id));target.innerHTML=`<h3>${edit?'Lid wijzigen':'Nieuw lid'}</h3><form id="memberForm" class="club-form"><input type="hidden" id="memberId" value="${esc(edit?.id||'')}"><div class="club-form two"><label>Naam<input id="memberName" required value="${esc(edit?.full_name||'')}"></label><label>E-mail<input id="memberEmail" type="email" value="${esc(edit?.email||'')}"></label><label>Telefoon<input id="memberPhone" type="tel" value="${esc(edit?.phone||'')}"></label><label class="member-admin-option"><input id="memberAdmin" type="checkbox" ${edit?.role==='admin'?'checked':''}> Admin</label></div><label><input id="memberActive" type="checkbox" ${edit?edit.active?'checked':'':'checked'}> Actief</label><div><strong style="font-size:9px">Teams</strong><div class="member-team-grid">${teams.map(t=>`<label class="member-team-option"><input type="checkbox" name="memberTeam" value="${t.id}" ${selectedTeams.has(t.id)?'checked':''}>${esc(t.team_name)}</label>`).join('')}</div></div><div class="club-actions"><button class="primary-button" type="submit">${edit?'Opslaan':'Lid toevoegen'}</button>${edit?'<button class="mini-button" type="button" id="memberCancel">Annuleren</button>':''}</div></form><h3>Leden</h3><div class="club-list">${members.map(m=>{const mts=memberTeamRows.filter(x=>x.member_id===m.id).map(x=>teams.find(t=>t.id===x.team_id)?.team_name).filter(Boolean);return `<div class="club-row"><div class="club-row-head"><div><strong>${esc(m.full_name||'(naam ontbreekt)')}</strong><small>${esc(m.email||m.phone||'Geen login-id')} · ${m.active?'Actief':'Inactief'}</small></div><span class="club-pill ${m.role==='admin'?'admin':''}">${m.role==='admin'?'Admin':'Lid'}</span></div><div>${mts.map(x=>`<span class="club-pill">${esc(x)}</span>`).join('')}</div><div class="mini-actions"><button class="mini-button" data-edit-member="${m.id}">Wijzigen</button></div></div>`}).join('')}</div>`;$('memberForm').onsubmit=saveMember;if($('memberCancel'))$('memberCancel').onclick=()=>renderAdminMembers();target.querySelectorAll('[data-edit-member]').forEach(b=>b.onclick=()=>{renderAdminMembers(b.dataset.editMember);requestAnimationFrame(()=>document.getElementById('memberForm')?.scrollIntoView({behavior:'smooth',block:'start'}));});}
async function saveMember(e){e.preventDefault();const id=$('memberId').value||null,payload={full_name:$('memberName').value.trim(),email:$('memberEmail').value.trim()||null,phone:$('memberPhone').value.trim()||null,role:$('memberAdmin').checked?'admin':'member',active:$('memberActive').checked};let memberId=id;if(id){const {error}=await supabase.from('members').update(payload).eq('id',id);if(error)return toast(error.message)}else{const {data,error}=await supabase.from('members').insert(payload).select().single();if(error)return toast(error.message);memberId=data.id}await supabase.from('member_teams').delete().eq('member_id',memberId);const teamIds=[...document.querySelectorAll('input[name="memberTeam"]:checked')].map(x=>x.value);if(teamIds.length){const {error}=await supabase.from('member_teams').insert(teamIds.map(team_id=>({member_id:memberId,team_id})));if(error)return toast(error.message)}if(payload.full_name){await supabase.from('task_assignments').update({assigned_member_id:memberId}).is('assigned_member_id',null).ilike('assigned_name',payload.full_name)}toast('Lid opgeslagen.');await loadBaseData();renderAdminMembers();}
function renderAdminAgenda(editTraining=''){const target=$('admin-agenda');const tr=trainings.find(x=>x.id===editTraining);target.innerHTML=`<h3>${tr?'Training wijzigen':'Training toevoegen'}</h3><form id="trainingForm" class="club-form"><input id="trainingId" type="hidden" value="${esc(tr?.id||'')}"><div class="club-form two"><label>Team<select id="trainingTeam">${teamOptions(tr?.team_id||'')}</select></label><label>Titel<input id="trainingTitle" value="${esc(tr?.title||'Training')}"></label><label>Datum<input id="trainingDate" type="date" required value="${esc(tr?.training_date||'')}"></label><label>Start<input id="trainingStart" type="time" required value="${esc(timeOnly(tr?.start_time||''))}"></label><label>Einde<input id="trainingEnd" type="time" value="${esc(timeOnly(tr?.end_time||''))}"></label><label>Locatie<input id="trainingLocation" value="${esc(tr?.location||'')}"></label></div><label>Opmerking<textarea id="trainingNotes">${esc(tr?.notes||'')}</textarea></label><div class="club-actions"><button class="primary-button" type="submit">Training opslaan</button>${tr?'<button class="mini-button" id="trainingCancel" type="button">Annuleren</button>':''}</div></form><h3>Taak/wedstrijd toevoegen</h3><form id="taskEventForm" class="club-form"><div class="club-form two"><label>Team<select id="taskTeam">${teamOptions()}</select></label><label>Datum<input id="taskDate" type="date" required></label><label>Aanwezig<input id="taskArrival" type="time"></label><label>Start wedstrijd<input id="taskStart" type="time" required></label><label>Thuis<input id="taskHome" required></label><label>Uit<input id="taskAway" required></label><label>Locatie<input id="taskLocation"></label><label>Veld<input id="taskField"></label></div><button class="primary-button" type="submit">Taakmoment toevoegen</button></form><h3>Beheeragenda</h3><div class="club-list" id="adminAgendaList">${trainings.map(t=>adminTrainingCard(t)).join('')}${taskEvents.map(t=>adminTaskCard(t)).join('')}</div>`;$('trainingForm').onsubmit=saveTraining;if($('trainingCancel'))$('trainingCancel').onclick=()=>renderAdminAgenda();$('taskEventForm').onsubmit=saveTaskEvent;target.querySelectorAll('[data-edit-training]').forEach(b=>b.onclick=()=>renderAdminAgenda(b.dataset.editTraining));target.querySelectorAll('[data-delete-training]').forEach(b=>b.onclick=()=>deleteTraining(b.dataset.deleteTraining));target.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=()=>deleteTaskEvent(b.dataset.deleteEvent));target.querySelectorAll('[data-add-assignment]').forEach(b=>b.onclick=()=>addAssignment(b.dataset.addAssignment));target.querySelectorAll('[data-save-assignment]').forEach(b=>b.onclick=()=>saveAssignment(b.dataset.saveAssignment));target.querySelectorAll('[data-delete-assignment]').forEach(b=>b.onclick=()=>deleteAssignment(b.dataset.deleteAssignment));}
function adminTrainingCard(t){return `<div class="club-row"><strong>Training · ${esc(t.title)}</strong><small>${esc(fmtDate(t.training_date))} · ${esc(timeOnly(t.start_time))} · ${esc(t.teams?.team_name||'Hele vereniging')} · ${esc(t.location||'')}</small><div class="mini-actions"><button class="mini-button" data-edit-training="${t.id}">Wijzigen</button><button class="mini-button danger" data-delete-training="${t.id}">Verwijderen</button></div></div>`}
function adminTaskCard(t){return `<div class="club-row"><strong>${esc(t.home)} — ${esc(t.away)}</strong><small>${esc(fmtDate(t.event_date))} · ${esc(timeOnly(t.start_time))} · ${esc(t.location||'')}</small>${(t.task_assignments||[]).map(a=>`<div class="assignment-row"><select id="assignmentMember-${a.id}">${memberOptions(a.assigned_member_id||'')}</select><select id="assignmentRole-${a.id}"><option value="referee" ${a.role==='referee'?'selected':''}>Scheidsrechter</option><option value="table" ${a.role==='table'?'selected':''}>Tafel</option><option value="other" ${a.role==='other'?'selected':''}>Overig</option></select><div><button class="mini-button" data-save-assignment="${a.id}">Opslaan</button><button class="mini-button danger" data-delete-assignment="${a.id}">×</button></div></div>`).join('')}<div class="mini-actions"><button class="mini-button" data-add-assignment="${t.id}">+ Toewijzing</button><button class="mini-button danger" data-delete-event="${t.id}">Taakmoment verwijderen</button></div></div>`}
async function saveTraining(e){e.preventDefault();const id=$('trainingId').value,p={team_id:$('trainingTeam').value||null,title:$('trainingTitle').value.trim()||'Training',training_date:$('trainingDate').value,start_time:$('trainingStart').value,end_time:$('trainingEnd').value||null,location:$('trainingLocation').value.trim()||null,notes:$('trainingNotes').value.trim()||null,created_by:member.id};const q=id?supabase.from('training_sessions').update(p).eq('id',id):supabase.from('training_sessions').insert(p);const {error}=await q;if(error)return toast(error.message);toast('Training opgeslagen.');await reloadDynamic();switchClubView('admin');}
async function deleteTraining(id){if(!confirm('Training verwijderen?'))return;const {error}=await supabase.from('training_sessions').delete().eq('id',id);if(error)return toast(error.message);await reloadDynamic();switchClubView('admin')}
async function saveTaskEvent(e){e.preventDefault();const p={team_id:$('taskTeam').value||null,event_date:$('taskDate').value,arrival_time:$('taskArrival').value||null,start_time:$('taskStart').value,home:$('taskHome').value.trim(),away:$('taskAway').value.trim(),location:$('taskLocation').value.trim()||null,field:$('taskField').value.trim()||null,active:true,created_by:member.id};const {error}=await supabase.from('task_events').insert(p);if(error)return toast(error.message);toast('Taakmoment toegevoegd. Voeg nu één of meer toewijzingen toe.');await reloadDynamic();switchClubView('admin')}
async function deleteTaskEvent(id){if(!confirm('Taakmoment en alle toewijzingen verwijderen?'))return;const {error}=await supabase.from('task_events').delete().eq('id',id);if(error)return toast(error.message);await reloadDynamic();switchClubView('admin')}
async function addAssignment(eventId){const ev=taskEvents.find(x=>x.id===eventId),used=(ev?.task_assignments||[]).map(a=>a.slot),slot=Math.max(0,...used)+1;const {error}=await supabase.from('task_assignments').insert({task_event_id:eventId,assigned_name:'Niet toegewezen',role:'other',slot});if(error)return toast(error.message);await reloadDynamic();switchClubView('admin')}
async function saveAssignment(id){const memberId=$(`assignmentMember-${id}`).value||null,m=members.find(x=>x.id===memberId),role=$(`assignmentRole-${id}`).value;const {error}=await supabase.from('task_assignments').update({assigned_member_id:memberId,assigned_name:m?.full_name||'Niet toegewezen',role}).eq('id',id);if(error)return toast(error.message);toast('Toewijzing opgeslagen.');await reloadDynamic();switchClubView('admin')}
async function deleteAssignment(id){const {error}=await supabase.from('task_assignments').delete().eq('id',id);if(error)return toast(error.message);await reloadDynamic();switchClubView('admin')}
function clearRealtime(){realtimeChannels.forEach(c=>supabase?.removeChannel(c));realtimeChannels=[]}
function setupRealtime(){if(!supabase||!member)return;const topic=`club-${member.id}-${Date.now()}-${Math.random().toString(36).slice(2)}`;const channel=supabase.channel(topic);channel.on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`recipient_member_id=eq.${member.id}`},reloadDynamic);channel.on('postgres_changes',{event:'*',schema:'public',table:'task_swap_requests'},reloadDynamic);channel.on('postgres_changes',{event:'*',schema:'public',table:'task_assignments'},reloadDynamic);channel.on('postgres_changes',{event:'*',schema:'public',table:'training_sessions'},reloadDynamic);realtimeChannels=[channel];channel.subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')console.warn('Realtime status:',status);});}
document.addEventListener('DOMContentLoaded',init);
})();