(()=>{
'use strict';
const U='https://elpnfmlrkoemjrnzaeok.supabase.co',K='sb_publishable_GPzLwaKeevg3e8CNjw9oAQ_50NW2xlg';
let sb=null,me=null,teams=[],trainerRows=[],members=[],timer=0;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function toast(x){const n=$('toast');if(!n)return alert(x);n.textContent=x;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2400)}
async function client(){if(sb)return sb;const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=mod.createClient(U,K,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});sb.auth.onAuthStateChange(()=>setTimeout(load,100));return sb}
async function load(){try{const s=await client(),{data:{session}}=await s.auth.getSession();if(!session){me=null;return schedule()}const {data:m,error}=await s.rpc('sync_current_member');if(error||!m?.active){me=null;return schedule()}me=m;const q=[s.from('teams').select('id,team_name').eq('active',true).order('team_name'),s.from('member_trainer_teams').select('member_id,team_id')];if(m.role==='admin')q.push(s.from('members').select('id,is_trainer'));const a=await Promise.all(q);teams=a[0].data||[];trainerRows=a[1].data||[];members=a[2]?.data||[];schedule()}catch(e){console.warn(e)}}
const trainerIds=id=>new Set(trainerRows.filter(x=>String(x.member_id)===String(id)).map(x=>String(x.team_id)));
function css(){if($('trainerMemberCss'))return;const s=document.createElement('style');s.id='trainerMemberCss';s.textContent='.trainer-check{display:flex!important;align-items:center;gap:9px;min-height:44px;font-size:14px!important;font-weight:750}.trainer-check input{width:22px!important;height:22px!important;margin:0!important}.trainer-teams{margin:12px 0}.trainer-teams>strong{display:block;font-size:14px;margin-bottom:8px}.trainer-grid{display:grid;gap:7px}.trainer-grid label{display:flex;align-items:center;gap:9px;border:1px solid var(--line);border-radius:11px;padding:9px 11px;font-size:12px;font-weight:700}.trainer-grid input{width:19px;height:19px;margin:0}';document.head.appendChild(s)}
function nav(){const n=document.querySelector('.tab[data-view="club"]');if(!n)return;let l=n.querySelector('.club-tab-label');if(!l){n.innerHTML='<span class="tab-icon">●</span><span class="club-tab-label"></span>';l=n.querySelector('.club-tab-label')}l.textContent=!me?'Club/inloggen':me.role==='admin'&&me.is_trainer?'Club/admin/trainer':me.role==='admin'?'Club/admin':me.is_trainer?'Club/trainer':'Club'}
function enhanceForm(){if(me?.role!=='admin')return;const f=$('memberForm');if(!f||f.dataset.trainerMember==='1')return;f.dataset.trainerMember='1';const id=$('memberId')?.value||'',row=members.find(x=>String(x.id)===String(id)),sel=trainerIds(id),two=f.querySelector('.club-form.two');if(two&&!$('memberTrainer')){const l=document.createElement('label');l.className='trainer-check';l.innerHTML=`<input id="memberTrainer" type="checkbox" ${row?.is_trainer?'checked':''}> Trainer`;two.appendChild(l)}$('memberActive')?.closest('label')?.classList.add('trainer-check');if(!$('trainerTeams')){const b=document.createElement('div');b.id='trainerTeams';b.className='trainer-teams';b.hidden=!row?.is_trainer;b.innerHTML=`<strong>Teams als trainer</strong><div class="trainer-grid">${teams.map(t=>`<label><input name="trainerTeam" type="checkbox" value="${esc(t.id)}" ${sel.has(String(t.id))?'checked':''}>${esc(t.team_name)}</label>`).join('')}</div>`;f.querySelector('.member-team-grid')?.parentElement?.insertAdjacentElement('afterend',b)}$('memberTrainer')?.addEventListener('change',e=>{$('trainerTeams').hidden=!e.target.checked});f.onsubmit=null;f.addEventListener('submit',save,true)}
async function save(e){e.preventDefault();e.stopImmediatePropagation();const s=await client(),id=$('memberId').value||null,p={full_name:$('memberName').value.trim(),email:$('memberEmail').value.trim()||null,phone:$('memberPhone').value.trim()||null,role:$('memberAdmin').checked?'admin':'member',is_trainer:!!$('memberTrainer')?.checked,active:$('memberActive').checked};let mid=id;if(id){const r=await s.from('members').update(p).eq('id',id);if(r.error)return toast(r.error.message)}else{const r=await s.from('members').insert(p).select().single();if(r.error)return toast(r.error.message);mid=r.data.id}const players=[...document.querySelectorAll('input[name="memberTeam"]:checked')].map(x=>x.value),trainers=p.is_trainer?[...document.querySelectorAll('input[name="trainerTeam"]:checked')].map(x=>x.value):[];let r=await s.from('member_teams').delete().eq('member_id',mid);if(r.error)return toast(r.error.message);if(players.length){r=await s.from('member_teams').insert(players.map(team_id=>({member_id:mid,team_id})));if(r.error)return toast(r.error.message)}r=await s.from('member_trainer_teams').delete().eq('member_id',mid);if(r.error)return toast(r.error.message);if(trainers.length){r=await s.from('member_trainer_teams').insert(trainers.map(team_id=>({member_id:mid,team_id})));if(r.error)return toast(r.error.message)}toast('Lid opgeslagen.');setTimeout(()=>location.reload(),250)}
function enhance(){css();nav();enhanceForm()}
function schedule(){clearTimeout(timer);timer=setTimeout(enhance,80)}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-edit-member],[data-adminview],[data-clubview]'))setTimeout(schedule,20)},true);
document.addEventListener('DOMContentLoaded',async()=>{css();new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});await load();schedule()});
})();