(()=>{
'use strict';

const U='https://elpnfmlrkoemjrnzaeok.supabase.co';
const K='sb_publishable_GPzLwaKeevg3e8CNjw9oAQ_50NW2xlg';
let sb=null,me=null,slots=[],periods=[],busy=false,agendaObserver=null,clubObserver=null,timer=0;
const $=id=>document.getElementById(id);
const season=()=>{const n=new Date(),y=n.getMonth()>=6?n.getFullYear():n.getFullYear()-1;return{label:`${y}-${y+1}`,start:`${y}-07-01`,end:`${y+1}-06-30`}};
function toast(m){const e=$('toast');if(!e)return alert(m);e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
async function client(){if(sb)return sb;const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=mod.createClient(U,K,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});return sb}
function periodFor(team){return periods.find(x=>String(x.team_id)===String(team)&&String(x.season_label)===season().label)||null}
function bounds(team){const p=periodFor(team),s=season();return{start:p?.first_training_date||s.start,end:p?.last_training_date||s.end,explicit:!!p}}
async function load(){if(busy)return;busy=true;try{const s=await client(),{data:{session}}=await s.auth.getSession();if(!session){me=null;slots=[];periods=[];return}const{data:m}=await s.rpc('sync_current_member');me=m?.active?m:null;if(!me)return;const [a,b]=await Promise.all([s.from('training_slots').select('id,team_id').eq('active',true),s.from('team_training_periods').select('*').eq('season_label',season().label)]);slots=a.data||[];periods=b.data||[];enhance();applyAgenda();trimTrainerDates()}catch(e){console.warn('Trainingsperiode laden',e)}finally{busy=false}}
function css(){if($('trainingPeriodsCss'))return;const s=document.createElement('style');s.id='trainingPeriodsCss';s.textContent=`.training-period-box{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:10px;border:1px solid var(--line);border-radius:12px;background:#f7f8fb}.training-period-box label{font-size:10px!important;font-weight:800!important;color:var(--muted)!important}.training-period-box input{width:100%;margin-top:4px;min-height:40px;border:1px solid var(--line);border-radius:10px;background:var(--card);padding:0 9px;font:inherit;font-size:12px;color:var(--ink)}.training-period-actions{grid-column:1/-1;display:flex;align-items:center;gap:8px;flex-wrap:wrap}.training-period-note{font-size:9px;color:var(--muted);font-weight:700}.trainer-period-empty{font-size:9px;color:#a34a00;font-weight:800;margin-top:6px}`;document.head.appendChild(s)}
function fillPeriod(team){const p=periodFor(team),start=$('trainingPeriodStart'),end=$('trainingPeriodEnd'),note=$('trainingPeriodNote');if(start)start.value=p?.first_training_date||'';if(end)end.value=p?.last_training_date||'';if(note)note.textContent=p?`Seizoen ${p.season_label}: ${p.first_training_date} t/m ${p.last_training_date}`:`Nog niet ingesteld; agenda gebruikt tijdelijk het volledige seizoen ${season().label}.`}
function enhance(){css();const host=$('weeklyTrainingAdminHost');if(!host)return;const panel=host.querySelector('.training-v2-panel');if(!panel)return;const h=panel.querySelector('h3');if(h&&h.textContent!=='Training agenda')h.textContent='Training agenda';const p=panel.querySelector(':scope > p');if(p)p.textContent='Kies per team de trainingsperiode, één of meerdere dagen en het tijdslot. Een team kan meerdere trainingen per week hebben.';const form=$('weeklyTrainingForm');const team=$('weeklyTeam');if(!form||!team)return;if(!$('trainingPeriodBox')){const box=document.createElement('div');box.id='trainingPeriodBox';box.className='training-period-box';box.innerHTML=`<label>Eerste training seizoen<input id="trainingPeriodStart" type="date"></label><label>Laatste training seizoen<input id="trainingPeriodEnd" type="date"></label><div class="training-period-actions"><button type="button" class="mini-button primary" id="saveTrainingPeriod">Periode opslaan</button><span class="training-period-note" id="trainingPeriodNote"></span></div>`;const teamLabel=team.closest('label');teamLabel?.insertAdjacentElement('afterend',box);$('saveTrainingPeriod')?.addEventListener('click',savePeriod);team.addEventListener('change',()=>setTimeout(()=>fillPeriod(team.value),0))}fillPeriod(team.value);trimTrainerDates()}
async function savePeriod(){if(me?.role!=='admin')return toast('Alleen een admin kan de trainingsperiode aanpassen.');const team=$('weeklyTeam')?.value||'',first=$('trainingPeriodStart')?.value||'',last=$('trainingPeriodEnd')?.value||'';if(!team)return toast('Kies een team.');if(!first||!last)return toast('Vul eerste en laatste training van het seizoen in.');if(last<first)return toast('De laatste training moet na de eerste training liggen.');const s=await client(),payload={team_id:team,season_label:season().label,first_training_date:first,last_training_date:last,updated_by:me.id,updated_at:new Date().toISOString()},{error}=await s.from('team_training_periods').upsert(payload,{onConflict:'team_id,season_label'});if(error)return toast(error.message);const i=periods.findIndex(x=>String(x.team_id)===String(team)&&String(x.season_label)===season().label);if(i>=0)periods[i]={...periods[i],...payload};else periods.push(payload);fillPeriod(team);applyAgenda();trimTrainerDates();toast('Trainingsperiode opgeslagen.')}
function cardDate(card){const day=card.closest('.day');return day?.dataset.agendaDate||day?.dataset.uxv3Date||''}
function slotFor(id){return slots.find(x=>String(x.id)===String(id))}
function applyAgenda(){const root=$('agendaList');if(!root)return;agendaObserver?.disconnect();for(const card of root.querySelectorAll('.agenda-training[data-training-slot]')){const slot=slotFor(card.dataset.trainingSlot),date=cardDate(card);if(!slot||!date){card.hidden=false;continue}const b=bounds(slot.team_id);card.hidden=date<b.start||date>b.end}observeAgenda()}
function trimTrainerDates(){for(const card of document.querySelectorAll('.trainer-v2-card[data-slot]')){const slot=slotFor(card.dataset.slot),sel=card.querySelector('[data-original]');if(!slot||!sel)continue;const b=bounds(slot.team_id);for(const option of [...sel.options])if(option.value<b.start||option.value>b.end)option.remove();let empty=card.querySelector('.trainer-period-empty');if(!sel.options.length){if(!empty){empty=document.createElement('div');empty.className='trainer-period-empty';empty.textContent='Geen training binnen de ingestelde seizoensperiode.';card.appendChild(empty)}card.querySelector('[data-save-override]')?.setAttribute('disabled','')}else{empty?.remove();card.querySelector('[data-save-override]')?.removeAttribute('disabled');sel.dispatchEvent(new Event('change'))}}}
function observeAgenda(){const root=$('agendaList');if(!root)return;if(!agendaObserver)agendaObserver=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(applyAgenda,100)});agendaObserver.disconnect();agendaObserver.observe(root,{childList:true,subtree:true})}
function observeClub(){const root=$('clubRoot');if(!root)return;clubObserver?.disconnect();clubObserver=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{enhance();trimTrainerDates()},90)});clubObserver.observe(root,{childList:true,subtree:true})}
function init(){css();observeAgenda();observeClub();document.addEventListener('click',e=>{if(e.target.closest?.('[data-adminview="agenda"],[data-clubview="trainer"],[data-weekly-edit]'))setTimeout(()=>{enhance();trimTrainerDates()},80)},true);document.addEventListener('training-data-changed',()=>setTimeout(load,80));load();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
