(()=>{
'use strict';
const U='https://elpnfmlrkoemjrnzaeok.supabase.co',K='sb_publishable_GPzLwaKeevg3e8CNjw9oAQ_50NW2xlg',F='52cfa65e-9782-4a81-ab35-e2f981fcb7a9',API='https://api.foys.io/competition/public-api/v1',STORE='basketballApp.selection.v3',CACHE='basketballApp.matches.v3.';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])),norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,''),d=v=>String(v||'').slice(0,10),t=v=>String(v||'').slice(0,5);
let sb=null,ctx=null,ctxAt=0,busy=false;const mc=new Map(),extra=new Map();
function season(){const n=new Date(),y=n.getMonth()>=6?n.getFullYear():n.getFullYear()-1;return{start:`${y}-07-01`,end:`${y+1}-06-30`}}
function sel(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function isArgon(v){return /^SV Argon(?:\s|$)/i.test(String(v||'').trim())}
function label(m,s){return[m?.[`${s}TeamSponsorClubName`]||m?.[`${s}Organisation`]?.name,m?.[`${s}TeamName`]].filter(Boolean).join(' ').trim()||'Onbekend team'}
function guid(m,s){return String(m?.[`${s}TeamGuid`]||'')}
function scored(m){return m?.homeScore!==null&&m?.homeScore!==undefined&&m?.awayScore!==null&&m?.awayScore!==undefined}
function addr(m){const a=m?.address||{},x=[a.address1,a.houseNumber,a.houseNumberExtension].filter(Boolean).join(' '),y=[a.zipCode,a.city].filter(Boolean).join(' ');return[x,y].filter(Boolean).join(', ')}
function day(v){return new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${d(v)}T12:00:00`)).toUpperCase()}
function short(v){return new Intl.DateTimeFormat('nl-NL',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${d(v)}T12:00:00`))}
function toast(x){const n=$('toast');if(!n)return alert(x);n.textContent=x;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
async function client(){if(sb)return sb;const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=mod.createClient(U,K,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});return sb}
async function context(force=false){if(!force&&ctx&&Date.now()-ctxAt<12000)return ctx;const s=await client(),{data:{session}}=await s.auth.getSession();if(!session)return ctx=null;const{data:m,error}=await s.rpc('sync_current_member');if(error||!m?.active)return ctx=null;const[pt,tt,slots,teams]=await Promise.all([s.from('member_teams').select('team_id,teams(id,team_name,foy_team_guid)').eq('member_id',m.id),s.from('member_trainer_teams').select('team_id,teams(id,team_name,foy_team_guid)').eq('member_id',m.id),s.from('training_slots').select('*,teams(id,team_name,foy_team_guid)').eq('active',true),s.from('teams').select('id,team_name,foy_team_guid').eq('active',true)]);const map=r=>(r.data||[]).map(x=>x.teams?{...x.teams,id:x.team_id}:null).filter(Boolean);ctx={member:m,memberTeams:map(pt),trainerTeams:map(tt),slots:slots.data||[],allTeams:teams.data||[]};ctxAt=Date.now();return ctx}
async function matches(g){if(!g)return[];if(mc.has(g))return mc.get(g);const q=season(),out=[];let skip=0,total=Infinity;while(skip<total){const p=new URLSearchParams({startDate:q.start,endDate:q.end,teamGuid:g,skipCount:String(skip),maxResultCount:'100',sorting:'date asc, startTime asc'}),r=await fetch(`${API}/matches?${p}`,{headers:{Accept:'application/json','X-FederationID':F},cache:'no-store'});if(!r.ok)break;const j=await r.json(),rows=j.items||[];out.push(...rows);total=Number(j.totalCount)||rows.length;skip+=rows.length;if(!rows.length||rows.length<100)break}mc.set(g,out);out.forEach(x=>extra.set(String(x.id),x));return out}
function stored(){const map=new Map(extra);for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith(CACHE))continue;try{for(const m of JSON.parse(localStorage.getItem(k)||'{}').matches||[])map.set(String(m.id),m)}catch{}}return map}
function css(){if($('uiReworkCss'))return;const s=document.createElement('style');s.id='uiReworkCss';s.textContent='.tabs{grid-template-columns:repeat(7,minmax(0,1fr))!important}.tabs .tab{font-size:6.4px!important;line-height:1.1}.club-tab-label{white-space:nowrap}.final-start{margin:4px 0 0!important;font-size:8px!important;color:var(--muted)!important}.player-count{display:inline!important;margin:0!important;font-size:inherit!important;font-weight:850!important;color:var(--navy)!important}.player-count.inline-count:before{content:" · ";font-weight:400;color:var(--muted)}.drive-toggle,.drive-toggle span{font-size:10px!important;font-weight:750!important}.drive-toggle input{width:20px!important;height:20px!important;margin:0!important}.badge-training{background:#eef1ff;color:var(--navy)}#admin-agenda.in-club-agenda{display:block!important;border-top:1px solid var(--line);margin-top:12px;padding-top:12px}#admin-agenda.in-club-agenda>h3:first-child{margin-top:0}.club-admin-agenda-note{font-size:9px;color:var(--muted);margin:8px 0}@media(max-width:480px){.tabs .tab{font-size:5.8px!important}}';document.head.appendChild(s)}
function polishCards(){const mm=stored();for(const c of document.querySelectorAll('#agendaList article[data-match-id],#gamesList article[data-match-id]')){const m=mm.get(String(c.dataset.matchId));if(m&&scored(m)){let st=c.querySelector('.final-start');if(!st){st=document.createElement('span');st.className='final-start'}st.textContent=`Start ${t(m.startTime)}`;c.querySelector('.time-col')?.appendChild(st)}const pc=c.querySelector('.player-count');if(pc){pc.classList.add('inline-count');const meta=c.querySelector('.meta'),br=meta?.querySelector('br');if(meta&&br)meta.insertBefore(pc,br);else meta?.appendChild(pc)}}}
function linked(c,title){const p=String(title||'').split(/\s+[—–-]\s+/),side=p.find(isArgon)||'',name=side.replace(/^SV Argon\s*/i,'').trim();return c.memberTeams.some(x=>norm(x.team_name)===norm(name))}
async function polishDetail(){const o=$('matchDetailOverlay');if(!o||o.hidden)return;const c=await context();if(!c)return;const body=$('matchDetailBody'),title=$('matchDetailTitle')?.textContent||'';if(!body)return;for(const p of body.querySelectorAll('p.match-muted'))if(/alleen beschikbaar voor teams waaraan je als lid|niet aan dit team gekoppeld/i.test(p.textContent||''))p.remove();for(const sec of body.querySelectorAll('.match-detail-section')){const h=sec.querySelector('h3')?.textContent?.trim();if((h==='Mijn wedstrijd'||h==='Aanwezigheid')&&!linked(c,title))sec.remove();if(h==='Taken'&&/geen clubtaken gekoppeld/i.test(sec.textContent||'')){const parts=title.split(/\s+[—–-]\s+/);if(parts.length>1&&isArgon(parts[1]))sec.remove()}}}
function mcard(m){const sc=scored(m)?`${m.homeScore} – ${m.awayScore}`:t(m.startTime),loc=[m.accommodationName,m.fieldName].filter(Boolean).join(' · '),a=addr(m);return`<article class="event rework-extra-match" data-match-id="${esc(m.id)}" data-rework-time="${esc(t(m.startTime))}"><div class="event-row"><div class="time-col"><div class="event-time${scored(m)?' score':''}">${esc(sc)}</div><span class="event-status">${scored(m)?'Eindstand':'Gepland'}</span></div><div class="event-main"><span class="badge ${scored(m)?'badge-final':'badge-game'}">${scored(m)?'Uitslag':'Wedstrijd'}</span><div class="match-title">${esc(label(m,'home'))} — ${esc(label(m,'away'))}</div>${scored(m)?`<div class="score-line">${esc(sc)}</div>`:''}<div class="meta">${esc(loc||'Locatie niet bekend')}${a?`<br>${esc(a)}`:''}</div><div class="competition">${esc(m.competition?.name||'')} · wedstrijd-ID ${esc(m.id)}</div></div></div></article>`}
function training(o){const s=o.slot;return`<article class="event rework-training" data-rework-time="${esc(t(s.start_time))}"><div class="event-row"><div class="time-col"><div class="event-time">${esc(t(s.start_time))}</div><span class="event-status">Training</span></div><div class="event-main"><span class="badge badge-training">Training</span><div class="match-title">SV Argon ${esc(s.teams?.team_name||'Team')}</div><div class="meta">${esc(t(s.start_time))} - ${esc(t(s.end_time))}${s.location?` · ${esc(s.location)}`:''}</div></div></div></article>`}
function getDay(root,date){let x=[...root.querySelectorAll('.day')].find(y=>y.dataset.reworkDate===date);if(x)return x;x=document.createElement('section');x.className='day';x.dataset.reworkDate=date;x.innerHTML=`<div class="day-head">${esc(day(date))}</div>`;root.appendChild(x);return x}
function occurrences(slots,start,end){const a=new Date(`${start}T12:00:00`),b=new Date(`${end}T12:00:00`),out=[];for(let x=new Date(a);x<=b;x.setDate(x.getDate()+1)){const wd=x.getDay()||7,date=x.toISOString().slice(0,10);for(const s of slots)if(Number(s.weekday)===wd)out.push({date,slot:s})}return out}
async function mainAgenda(){const root=$('agendaList'),c=await context();if(!root||!c)return;root.querySelectorAll('.rework-extra-match,.rework-training').forEach(x=>x.remove());const mm=stored();for(const dayEl of root.querySelectorAll('.day')){if(dayEl.dataset.reworkDate)continue;const card=dayEl.querySelector('[data-match-id]'),m=card?mm.get(String(card.dataset.matchId)):null;if(m)dayEl.dataset.reworkDate=d(m.date)}const s=sel(),all=String(s?.teamGuid||'').startsWith('all-'),guids=[...new Set([...c.memberTeams,...c.trainerTeams].map(x=>x.foy_team_guid).filter(Boolean))];if(!all&&s?.teamGuid)guids.push(s.teamGuid);const existing=new Set([...root.querySelectorAll('[data-match-id]')].map(x=>String(x.dataset.matchId)));for(const g of [...new Set(guids)])for(const m of await matches(g)){if(existing.has(String(m.id)))continue;existing.add(String(m.id));const w=document.createElement('div');w.innerHTML=mcard(m);getDay(root,d(m.date)).appendChild(w.firstElementChild)}const ids=new Set([...c.memberTeams,...c.trainerTeams].map(x=>x.id));if(s?.teamGuid&&!all){const tm=c.allTeams.find(x=>String(x.foy_team_guid)===String(s.teamGuid));if(tm)ids.add(tm.id)}const q=season(),today=new Date().toISOString().slice(0,10);for(const o of occurrences(c.slots.filter(x=>ids.has(x.team_id)),today,q.end)){const w=document.createElement('div');w.innerHTML=training(o);getDay(root,o.date).appendChild(w.firstElementChild)}for(const dayEl of root.querySelectorAll('.day')){const cards=[...dayEl.querySelectorAll(':scope>article.event')];cards.sort((a,b)=>{const ma=a.dataset.matchId?stored().get(String(a.dataset.matchId)):null,mb=b.dataset.matchId?stored().get(String(b.dataset.matchId)):null;return(t(ma?.startTime)||a.dataset.reworkTime||'99:99').localeCompare(t(mb?.startTime)||b.dataset.reworkTime||'99:99')}).forEach(x=>dayEl.appendChild(x))}const days=[...root.querySelectorAll('.day')];days.sort((a,b)=>(a.dataset.reworkDate||'9999').localeCompare(b.dataset.reworkDate||'9999')).forEach(x=>root.appendChild(x));polishCards()}
async function presence(force=false){const target=$('club-sub-presence');if(!target||(!force&&!target.classList.contains('active')))return;const c=await context(force);if(!c)return;const map=new Map(c.memberTeams.map(x=>[String(x.foy_team_guid),x])),games=new Map(),today=new Date().toISOString().slice(0,10);for(const tm of c.memberTeams)for(const m of await matches(tm.foy_team_guid))if(d(m.date)>=today)games.set(String(m.id),m);const s=await client(),{data:ats}=await s.from('attendance').select('foy_match_id,attending,driving').eq('member_id',c.member.id),am=new Map((ats||[]).map(x=>[String(x.foy_match_id),x])),rows=[...games.values()].sort((a,b)=>`${d(a.date)}T${t(a.startTime)}`.localeCompare(`${d(b.date)}T${t(b.startTime)}`));target.innerHTML=`<div class="club-card-panel"><h2>Aanwezigheid</h2><p>Kies per wedstrijd Ja of Nee. Dit is dezelfde aanwezigheid als bij de wedstrijd in Agenda en Wedstrijden.</p><div class="club-list">${rows.length?rows.map(m=>{const g=[guid(m,'home'),guid(m,'away')].find(x=>map.has(x)),tm=map.get(g),v=am.get(String(m.id))?.attending;return`<div class="club-row"><strong>${esc(label(m,'home'))} — ${esc(label(m,'away'))}</strong><small>${esc(short(m.date))} · ${esc(t(m.startTime))} · ${esc(m.accommodationName||'')}</small><div class="attendance-choice"><button class="mini-button yes ${v===true?'selected':''}" data-rw-att="yes" data-mid="${esc(m.id)}" data-tid="${esc(tm?.id||'')}">Ja</button><button class="mini-button no ${v===false?'selected':''}" data-rw-att="no" data-mid="${esc(m.id)}" data-tid="${esc(tm?.id||'')}">Nee</button></div></div>`}).join(''):'<div class="club-empty">Geen komende wedstrijden voor jouw teams.</div>'}</div></div>`;target.querySelectorAll('[data-rw-att]').forEach(b=>b.onclick=async()=>{const yes=b.dataset.rwAtt==='yes',old=am.get(String(b.dataset.mid)),{error}=await s.rpc('set_match_attendance',{p_match_id:Number(b.dataset.mid),p_team_id:b.dataset.tid,p_attending:yes,p_driving:yes&&old?.driving===true});if(error)return toast(error.message);toast(yes?'Aanwezig: Ja':'Aanwezig: Nee');await presence(true);setTimeout(run,100)})}
function clubAdmin(){const tabs=$('clubTabs'),admin=tabs?.querySelector('[data-clubview="admin"]'),agenda=tabs?.querySelector('[data-clubview="clubagenda"]');if(admin&&agenda)tabs.insertBefore(admin,agenda);const button=$('adminTabs')?.querySelector('[data-adminview="agenda"]'),adminAgenda=$('admin-agenda'),club=$('club-sub-clubagenda')?.querySelector('.club-card-panel');if(button)button.style.display='none';if(!adminAgenda||!club)return;if(!adminAgenda.classList.contains('in-club-agenda')){adminAgenda.classList.add('in-club-agenda');adminAgenda.hidden=false;const note=document.createElement('p');note.className='club-admin-agenda-note';note.textContent='Beheer trainingen en taken direct vanuit dezelfde Clubagenda.';club.append(note,adminAgenda)}adminAgenda.hidden=false;const h=[...adminAgenda.querySelectorAll(':scope>h3')].find(x=>x.textContent.trim()==='Beheeragenda');if(h)h.textContent='Taken beheren'}
async function run(force=false){if(busy)return;busy=true;try{css();clubAdmin();polishCards();await polishDetail();if($('view-agenda')?.classList.contains('active'))await mainAgenda();if($('club-sub-presence')?.classList.contains('active'))await presence(force)}catch(e){console.warn('UI rework',e)}finally{busy=false}}
function schedule(force=false){clearTimeout(schedule.id);schedule.id=setTimeout(()=>run(force),180)}
document.addEventListener('DOMContentLoaded',()=>{css();schedule(true);document.addEventListener('change',e=>{if(e.target.id==='teamSelect'){mc.clear();setTimeout(()=>schedule(true),400)}});new MutationObserver(()=>schedule()).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class','hidden']});setInterval(()=>{if($('view-agenda')?.classList.contains('active')||$('view-club')?.classList.contains('active'))schedule()},4000)});
})();